Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConsumeGoogleAPI.Models
{
    public class Book
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string SmallImageLink { get; set; }
        public List<string> Authors { get; set; }
        public string Publisher { get; set; }
        public string PublishedDate { get; set; }
        public string Description { get; set; }
        public string ISBN10 { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace ConsumeGoogleApi.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Text.Json;
using System.Text;
using ConsumeGoogleAPI.Models;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
using System.IO;
using ConsumeGoogleApi.Models;
using System.Diagnostics;

namespace ConsumeGoogleAPI.Controllers
{
    public class BooksController : Controller
    {
        const string BASE_URL = "https://www.googleapis.com/books/v1/";

        private readonly ILogger<BooksController> _logger;

        private readonly IHttpClientFactory _clientFactory;

        public IEnumerable<Book> Books { get; set; }

        public bool GetStudentsError { get; private set; }

        public BooksController(ILogger<BooksController> logger, IHttpClientFactory clientFactory)
        {
            _logger = logger;
            _clientFactory = clientFactory;
        }

        private async Task<IEnumerable<Book>> GetBooks()
        {

            IList<Book> Books = new List<Book>();

            var message = new HttpRequestMessage();
            message.Method = HttpMethod.Get;
            message.RequestUri = new Uri($"{BASE_URL}volumes?q=harry+potter");
            message.Headers.Add("Accept", "application/json");

            var client = _clientFactory.CreateClient();

            var response = await client.SendAsync(message);


            if (response.IsSuccessStatusCode)
            {
                using var responseStream = await response.Content.ReadAsStreamAsync();
                string JsonString = StreamToString(responseStream);
                dynamic myJObject = JObject.Parse(JsonString);
                dynamic Tuples = myJObject.items;
                for (int i = 0; i < Tuples.Count; i++)
                {
                    string id = Tuples[i].id;
                    string title = Tuples[i].volumeInfo.title;
                    string smallImageLink = Tuples[i].volumeInfo.imageLinks.smallThumbnail;
                    dynamic listAuthors = Tuples[i].volumeInfo.authors;
                    List<string> authors = new List<string>();
                    for (int j = 0; j < listAuthors.Count; j++)
                    {
                        string authorName = listAuthors[j];
                        authors.Add(authorName);
                    }
                    string publisher = Tuples[i].volumeInfo.publisher;
                    string publishedDate = Tuples[i].volumeInfo.publishedDate;
                    string description = Tuples[i].volumeInfo.description;
                    string iSBN10 = Tuples[i].volumeInfo.industryIdentifiers[1].identifier;
                    Book book = new Book { Id = id, Title = title, SmallImageLink = smallImageLink, Authors = authors, Publisher = publisher, PublishedDate = publishedDate, Description = description, ISBN10 = iSBN10 };
                    Books.Add(book);
                }
            }
            else
            {
                GetStudentsError = true;
                Books = Array.Empty<Book>();
            }
            return Books;
        }
        public string StreamToString(Stream stream)
        {
            stream.Position = 0;
            using (StreamReader reader = new StreamReader(stream, Encoding.UTF8))
            {
                return reader.ReadToEnd();
            }
        }

        public async Task<IActionResult> Index()
        {
            Books = await GetBooks();

            return View(Books);
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = new HttpRequestMessage();
            message.Method = HttpMethod.Get;
            message.RequestUri = new Uri($"{BASE_URL}volumes/" + id);
            message.Headers.Add("Accept", "application/json");

            var client = _clientFactory.CreateClient();

            var response = await client.SendAsync(message);

            Book book = null;

            if (response.IsSuccessStatusCode)
            {
                using var responseStream = await response.Content.ReadAsStreamAsync();
                string JsonString = StreamToString(responseStream);
                dynamic Tuples = JObject.Parse(JsonString);
                string title = Tuples.volumeInfo.title;
                string smallImageLink = Tuples.volumeInfo.imageLinks.smallThumbnail;
                dynamic listAuthors = Tuples.volumeInfo.authors;
                List<string> authors = new List<string>();
                for (int j = 0; j < listAuthors.Count; j++)
                {
                    string authorName = listAuthors[j];
                    authors.Add(authorName);
                }
                string publisher = Tuples.volumeInfo.publisher;
                string publishedDate = Tuples.volumeInfo.publishedDate;
                string description = Tuples.volumeInfo.description;
                string iSBN10 = Tuples.volumeInfo.industryIdentifiers[1].identifier;
                book = new Book { Id = id, Title = title, SmallImageLink = smallImageLink, Authors = authors, Publisher = publisher, PublishedDate = publishedDate, Description = description, ISBN10 = iSBN10 };
            }
            else
            {
                GetStudentsError = true;
            }

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ConsumeGoogleAPI.Models;
using ConsumeGoogleApi.Models;

namespace ConsumeGoogleAPI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Books/Details.cshtml
@model ConsumeGoogleAPI.Models.Book

@{
    ViewData["Title"] = "Book Details";
}

<h3>@ViewData["Title"]</h3>

<div>
    <hr />
    <div>
        <img src="@Url.Content(Model.SmallImageLink)" alt="Image" />
    </div>
    <br />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Authors)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Authors)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Publisher)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublishedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublishedDate)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN10)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ISBN10)
        </dd>
    </dl>
</div>

Views/Books/Index.cshtml
@model IEnumerable<ConsumeGoogleAPI.Models.Book>
@{
    ViewData["Title"] = "Harry Potter Books Information";
}

<div>
    <h3 class="display-4">@ViewData["Title"]</h3>
    <br />
    <br />
    <ul>
        @foreach (var item in Model)
        {
            <li>
                <a asp-controller="Books"
                   asp-action="Details"
                   asp-route-id="@item.Id">
                    @item.Title
            </a>
        </li>
    }
    </ul>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Amandeep Singh Janjua</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Amandeep Singh Janjua</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if(User.Identity.IsAuthenticated){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books Info</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ConsumeGoogleApi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>